apiVersion: v1
kind: ConfigMap
metadata:
  name: kitos-api-config
  namespace: kitos
  labels:
    app.kubernetes.io/name: kitos-api
    app.kubernetes.io/part-of: kitos
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Database__Provider: "PostgreSql"
  AppSettings__BaseUrl: "https://kitos.example.dk"
  AppSettings__SsoCertFilePath: "/etc/ssl/certs/sso-sp.pfx"
  AppSettings__StsCertFilePath: "/etc/ssl/certs/sts.pfx"
  AppSettings__StsOrganisationCertFilePath: "/etc/ssl/certs/sts-org.pfx"
