apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    easyhosting.io/service-reference: PubSub.Application.Api/Dockerfile
    easyhosting.io/service-unique-id: bbc16f0d-0692-4131-afe7-29f4cf875d2f
    easyhosting.io/easy-hosting-domain-name: bbc16f0d-0692-4131-afe7-29f4cf875d2f.kitos-dev.strongminds.easyhosting.strongminds.dev
  labels:
    app: kitos-pubsub
  name: kitos-pubsub
  namespace: kitos
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kitos-pubsub
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: monitoring/sidecar-otel-collector
      labels:
        app: kitos-pubsub
    spec:
      containers:
      - env: []
        image: '{will be replaced by build pipeline}'
        name: kitos-pubsub
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 100m
      imagePullSecrets:
      - name: 90d73529-a238-405b-a079-3eea2e8e36e6