apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pubsub-dev-db
  namespace: kitos
  labels:
    app.kubernetes.io/managed-by: easyhosting
    easyhosting.io/resource-kind: database-server
    easyhosting.io/resource-id: "1c71f2b5b16d4ff99fd447de2134afcc"
    easyhosting.io/application-id: "kitos"
  annotations:
    easyhosting.io/display-name: "pubsub-dev-db"
    easyhosting.io/manifest-path: "infrastructure/kitos-dev/kitos/databases/pubsub-dev-db/cluster.yaml"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
  storage:
    size: 5Gi