apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pubsub-dev-db
  namespace: kitos
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: pubsub-dev-db
      owner: postgres
      secret:
        name: cnpg-bootstrap-secret-pubsub-dev-db
  storage:
    size: 5Gi