apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database-65b16ad17e9c4905bddb571f7e6fe53d
  namespace: kitos
  labels:
    app.kubernetes.io/managed-by: easyhosting
    easyhosting.io/resource-kind: database
    easyhosting.io/resource-id: "65b16ad17e9c4905bddb571f7e6fe53d"
    easyhosting.io/database-server-id: "3d41c24a0af84c85a86d77591cf3a563"
    easyhosting.io/application-id: "kitos"
  annotations:
    easyhosting.io/display-name: "dev-db"
    easyhosting.io/manifest-path: "infrastructure/kitos-dev/kitos/database-servers/kitos-databases/databases/dev-db/database.yaml"
spec:
  name: dev-db
  cluster:
    name: kitos-databases
  owner: kitos
  ensure: present