apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kitos-ingress
  namespace: kitos
  labels:
    app.kubernetes.io/part-of: kitos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kitos.example.dk
      secretName: kitos-tls
  rules:
    - host: kitos.example.dk
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kitos-api
                port:
                  number: 8080
          - path: /odata
            pathType: Prefix
            backend:
              service:
                name: kitos-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kitos-api
                port:
                  number: 8080
