// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubSub.Infrastructure.DataAccess;

#nullable disable

namespace PubSub.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(PubSubContext))]
    [Migration("20250409135507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PubSub.Core.Models.Subscription", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Callback")
                        .IsRequired();

                    b.Property<string>("OwnerId")
                        .IsRequired();

                    b.Property<string>("Topic")
                        .IsRequired();

                    b.HasKey("Uuid");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
