apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hangfire-dev-db
  namespace: kitos
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: hangfire-dev-db
      owner: kitos
      secret:
        name: cnpg-bootstrap-secret-hangfire-dev-db
  storage:
    size: 5Gi
backup:
  target: primary
  barmanObjectStore:
    destinationPath: s3://easyhosting-postgres-backups/kitos/hangfire-dev-db
    endpointURL: 
    s3Credentials:
      accessKeyId:
        name: easyhosting-postgres-backup-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: easyhosting-postgres-backup-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  retentionPolicy: "31d"