apiVersion: easyhosting.io/v1alpha1
kind: PostgresDatabase
metadata:
  name: dev-db
  namespace: kitos
spec:
  mode: managed
  engine: cloudnativepg
  version: "17"
  database: dev-db
  storage: 5Gi
  backupPolicy: standard