apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dev-db-daily
  namespace: kitos
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: dev-db
  method: barmanObjectStore