apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: aln-test-db
  namespace: kitos
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  bootstrap:
    initdb:
      database: aln-test-db
      owner: kitos
      secret:
        name: cnpg-bootstrap-secret-aln-test-db
  storage:
    size: 5Gi