// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RemovedHasMainContract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedHasMainContract));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Infrastructure.DataAccess/Migrations/202209140750404_RemovedHasMainContract.Designer.cs
            get { return "202209140750404_RemovedHasMainContract"; }
========
            get { return "202209091039005_add_itcontract_read_model"; }
>>>>>>>> feature/KITOSUDV-3211-merge-fix:Infrastructure.DataAccess/Migrations/202209091039005_add_itcontract_read_model.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
