// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class DPR_OversightReportLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DPR_OversightReportLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "202509290929471_DPR_OversightReportLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
