// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Usage_catalogArchiveDuty_indices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usage_catalogArchiveDuty_indices));
        
        string IMigrationMetadata.Id
        {
            get { return "202502121305265_Usage_catalogArchiveDuty_indices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
