// <auto-generated />
namespace Infrastructure.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddExternalAndInternalPaymentOrganizationUnits_ToContractReadModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExternalAndInternalPaymentOrganizationUnits_ToContractReadModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202604071741464_AddExternalAndInternalPaymentOrganizationUnits_ToContractReadModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
